### ISSUE TITLE
DC Mouse Issue

### ISSUE THREAD

**Issue by MoeFoh** [jnmartin84/doom64-dc#25]
No **FORWARD** movement. BACK movement OK. (y-axis)
Also, LEFT/RIGHT movement OK. (x-axis)

Edit: More testing. Actually, FORWARD moves BACK & BACK moves BACK.

On menus: DOWN moves pointer DOWN & UP moves pointer DOWN.

FYI: Keyboard testing, all good.

Edit:
Fixed:
Changed:
} else if(last_joyy > -128) {
to:
} else if(last_joyy < -128) {
in i_main.c

**Comment by jnmartin84** [comment]
Could you make a pull request

**Comment by MoeFoh** [comment]
> Could you make a pull request

I have no idea how to do that.

**Comment by jnmartin84** [comment]
I don't have a mouse but I will try to find people that do and see if this looks right to them

**Comment by MoeFoh** [comment]
You can test using Windows demul. Set controller 2 to mouse.

**Comment by jnmartin84** [comment]
Closed with your pr
