### ISSUE TITLE
Triggers Pull Up Map During Combat

### ISSUE THREAD

**Issue by XD3l** [jnmartin84/doom64-dc#4]
This isn't so much of a bug as it is a change request. 

When in heavy combat, I tend to hold both triggers at the same time while strafing because I let go of one while I am pulling the other. This of course keeps pulling up the map and getting me killed. So can we change the MAP to WEAPON UP + WEAPON DOWN or any button + START? Something that won't get in the way?

I tried to set up the dev environment to make my own custom build but I get this error after typing "make".

"curl: (28) Failed to connect to ftpmirror.gnu.org port 443 after 130913 ms: Connection timed out
make: *** [scripts/download.mk:106: gcc-13.2.0.tar.xz] Error 28"

**Comment by jnmartin84** [comment]
I can't help with the toolchain issue but this has been suggested before and I was going to look into control improvements. Biggest issue is being two buttons short. Of all the combos to pick that's probably the least unreasonable one.

**Comment by jnmartin84** [comment]
@Immorpher  I know you mentioned using the d-pad for extra buttons at one point. I personally like to use the d-pad over the control stick. Maybe I can do something with the control defaults and we can come up with some that use dpad for move and some that don't? Would that work on N64? If it does it'll work here too

**Comment by gyrovorbis** [comment]
@XD3l Toolchain issues should get reported to the KallistiOS repo.... but that one looks fairly common. I would try it again, if I were you, sometimes the GCC servers go down for maintenance, and then the build scripts will fail when trying to download the source code... Probably all that happened here!

**Comment by MoeFoh** [comment]
> This isn't so much of a bug as it is a change request.
> 
> When in heavy combat, I tend to hold both triggers at the same time while strafing because I let go of one while I am pulling the other. This of course keeps pulling up the map and getting me killed. So can we change the MAP to WEAPON UP + WEAPON DOWN or any button + START? Something that won't get in the way?
> 
> I tried to set up the dev environment to make my own custom build but I get this error after typing "make".
> 
> "curl: (28) Failed to connect to ftpmirror.gnu.org port 443 after 130913 ms: Connection timed out make: *** [scripts/download.mk:106: gcc-13.2.0.tar.xz] Error 28"

Check Makefile.cfg in dc-chain dir. Try wget & enable the alt domain line.

**Comment by jnmartin84** [comment]
changed automap to X+Y combined press
